# Generated by Django 5.2.2 on 2025-07-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=200)),
                ('item_discrption', models.CharField(max_length=300)),
                ('item_image', models.CharField(default='https://idacademyonline.com/wp-content/uploads/2019/01/Image-Coming-Soon-ECC.png', max_length=500)),
                ('item_price', models.IntegerField()),
                ('item_qty', models.IntegerField()),
                ('item_color', models.CharField(max_length=50)),
                ('item_fabric', models.CharField(max_length=100)),
                ('item_Stiching', models.CharField(max_length=100)),
            ],
        ),
    ]
