# Generated by Django 5.2.2 on 2025-08-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='item_image2',
            field=models.CharField(default='https://idacademyonline.com/wp-content/uploads/2019/01/Image-Coming-Soon-ECC.png', max_length=500),
        ),
        migrations.AddField(
            model_name='store',
            name='item_image3',
            field=models.CharField(default='https://idacademyonline.com/wp-content/uploads/2019/01/Image-Coming-Soon-ECC.png', max_length=500),
        ),
        migrations.AddField(
            model_name='store',
            name='item_image4',
            field=models.CharField(default='https://idacademyonline.com/wp-content/uploads/2019/01/Image-Coming-Soon-ECC.png', max_length=500),
        ),
    ]
