# Generated by Django 5.2.2 on 2025-08-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200)),
                ('c_number', models.CharField(max_length=200)),
                ('c_mail', models.CharField(max_length=200)),
                ('c_subject', models.CharField(max_length=500)),
                ('c_message', models.CharField(max_length=900)),
            ],
        ),
    ]
