# Generated by Django 5.2.2 on 2025-08-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='c_mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='c_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='c_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='c_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='c_subject',
            new_name='subject',
        ),
    ]
